### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by Grayson1337** [Grayson1337/CP2Project#1]
can you add a line of code into the book class?

**Comment by OAA97** [comment]
do this?

**Comment by OAA97** [comment]
WHAT THE FUCK IS GOING OOOOOOOOOOOOOOOOONNNN!!!!!!

**Comment by Grayson1337** [comment]
bruh add a line of code

**Comment by OAA97** [comment]
random

**Comment by Grayson1337** [comment]
nice feature
